export const projects = [
  {
    title: 'DALL-E AI',
    description: "The Community Showcase.Browse through a collection of imaginative and visually stunning images generated by DALL-E AI.",
      image: '/images/Untitled.jpg',
      tags: ['OpenAI', 'Mongo', 'Express', 'React', 'Node', 'Cloudinary'],
    source: 'https://aidalle.vercel.app/',
    visit: 'https://github.com/yolojewjitsu/aidalle',
    id: 0,
  },
  {
    title: 'Codex - Your AI',
    description:"Codex is a revolutionary AI app that harnesses the power of ChatGPT, a large language model trained by OpenAI, to provide users with unparalleled assistance in a variety of tasks. Whether you need help with research, writing, or just want to have a conversation, Codex is here to assist you.",
    image: '/images/codex.jpg',
    tags: ['OpenAI', 'Node', 'JavaScript'],
    source: 'https://codex-seven-psi.vercel.app/',
    visit: 'https://github.com/yolojewjitsu/codex',
    id: 1,
  },
];

export const TimeLineData = [
  { year: 2021, text: 'Started my career', },
];